@startuml Пример C4: Контекст
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title  Фриланс биржа - Контекстная диаграмма

Person(исполнитель, "исполнитель", "Выполняет таски")
Person(заказчик, "Заказчик", "Отслеживает заказы и управляет ими")
Person(админ, "Админ", "Модерирует пользователей и заказы")

System(фриланс_система, "Система управления заказами", "Обеспечивает полный цикл от работами с заказами: создание, просмотр, завершения, модерация")

System_Ext(платежный_шлюз, "Платежный шлюз", "Внешняя система обработки онлайн-платежей")
System_Ext(верификатор_документов, "Верификатор документов", "Внешняя служба проверка подлинности докуметнов")

Rel(исполнитель, фриланс_система, "Выполняет заказы", "HTTPS")
Rel(заказчик, фриланс_система, "Создает заказы", "HTTPS")
Rel(админ, фриланс_система, "модерирует заказы и пользователей", "HTTPS")
Rel(фриланс_система, платежный_шлюз, "Передает данные для списания или зачисления средств", "API/HTTPS")
Rel(фриланс_система, верификатор_документов, "Передает документы для пороверки", "API/HTTPS")

@enduml